language: node_js

node_js:
  - "10"

branches:
  only:
    - development
   
services : 
  - mongodb
  - redis-server
  
env:
  - MONGO_URL = 'mongodb://admin:YanaGeras12061996@ds147926.mlab.com:47926/paper-games-test'
  - REDIS_URL=redis://127.0.0.1:6379
  - JWT_SECRET=YanaGeras12061996
  `
cache:
  directories:
  - server/node_modules
  - client/node_modules
  
install:
  - npm test
  
before_deploy:
  - git config --global user.password "19961996yankayanka"
  - git config --global user.username "gerasyana"
  - mv herokuDeploy/.gitignore .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  target_branch : heroku
  on:
    branch : development
  
  

