language: node_js
node_js:
  - "10"

    
cache:
  directories:
  - server/node_modules
  - client/node_modules
  
services : 
  - mongodb
  - redis-server
  
install:
  - npm run build-client
  
before_deploy:
  - git config --global user.password "19961996yankayanka"
  - git config --global user.username "gerasyana"
  - mv herokuDeploy/.gitignore .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github-token
  target_branch : heroku
  on:
    branch : development
  

