language: node_js
node_js:
  - "10"
  
 branches:
  only:
    - heroku
    - development
    
cache:
  directories:
  - server/node_modules
  - client/node_modules
  
services : 
  - mongodb
  - redis-server
  
install:
  - npm run build-client
  
before_deploy:
  - mv herokuDeploy/.gitignore .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github-token
  on:
    branch : heroku

