language: node_js
node_js:
  - "10"
  
cache:
  directories:
  - server/node_modules
  - client/node_modules
  
services : 
  - mongodb
  - redis-server
  
install:
  - npm run build-client
  
before_deploy:
 - mv herokuDeploy/.gitignore .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github-token
  local_dir: build
  on:
    branch: heroku-server
