language: node_js

node_js:
  - "10"

branches:
  only:
    - development
    
cache:
  directories:
  - server/node_modules
  - client/node_modules
  
install:
  - npm run build-client
  
before_deploy:
  - git config --global user.password "19961996yankayanka"
  - git config --global user.username "gerasyana"
  - mv herokuDeploy/.gitignore .gitignore

deploy:
  - provider : heroku
    app : paper-games
    api_key : $heroku_token
    on : production
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    target_branch : heroku
    on:
      branch : development
  
  

