export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const AUTH_SET_TIMEOUT = 'AUTH_SET_TIMEOUT';

export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

