export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const AUTH_SET_TIMEOUT = 'AUTH_SET_TIMEOUT';

export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SET_AUTH_REDIRECT_URL = 'SET_AUTH_REDIRECT_URL';

export const SET_SITE_STATISTICS = 'SET_SITE_STATISTICS';
export const UPDATE_ROOMS = 'UPDATE_ROOMS';

export const JOIN_ROOM = 'JOIN_ROOM';
export const CREATE_ROOM = 'CREATE_ROOM';
export const PLAYER1_JOINED = 'PLAYER1_JOINED';
export const PLAYER2_JOINED = 'PLAYER2_JOINED';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const CLOSE_GAME = 'CLOSE_GAME';
export const PLAYER_LEFT_GAME = 'PLAYER_LEFT_GAME';
export const PLAYER_MADE_MOVE = 'PLAYER_MADE_MODE';
export const UPDATE_GAME_BOARD = 'UPDATE_GAME_BOARD';

